server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
          username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
          password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
  security:
    username: ${SPRING_SECURITY_USERNAME}
    password: ${SPRING_SECURITY_PASSWORD}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE}