server:
  port: 8001

spring:
  application:
    name: note
  profiles:
    active: dev
  config:
    import: optional:configserver:http://admin:1234@localhost:8888

#창휘 로컬 네오4제이 테스트용
  neo4j:
    authentication:
      username: neo4j
      password: admin1234
    uri: bolt://localhost:7687

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

