server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: note
          uri: lb://NOTE
          predicates:
            - Path=/api/user/**,/api/note/**
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/auth/**
#        - id: gpt
#          uri: lb://GPT
#          predicates:
#            - name: gpt
#              args:
#                pattern: /api/gpt/**
        - id: s3
          uri: lb://S3
          predicates:
            - Path=/api/s3
#        - id: ocr
#          uri: lb://OCR
#          predicates:
#            - name: ocr
#              args:
#                pattern: /api/ocr/**
#        - id: sfu
#          uri: lb://SFU
#          predicates:
#            - name: sfu
#              args:
#                pattern: /socket.io/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
