server:
  port: 8000

spring:
  application:
    name: gateway
  profiles:
    active: prod
  config:
    import: ${SPRING_CONFIG_IMPORT}
  cloud:
    gateway:
      routes:
        - id: note
          uri: lb://NOTE
          predicates:
            - Path=/api/user/**,/api/space/**,/api/page/**,/api/note/**,/api/folder/**,/api/like/**,/api/trash/**
          filters:
            - name: TokenValidationCheckFilter
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/auth/**
        - id: gpt
          uri: lb://GPT
          predicates:
            - Path=/api/gpt/**
          filters:
            - name: TokenValidationCheckFilter
        - id: s3
          uri: lb://S3
          predicates:
            - Path=/api/s3/**
          filters:
            - name: TokenValidationCheckFilter
        - id: ocr
          uri: lb://OCR
          predicates:
            - Path=/api/ocr/**
          filters:
            - name: TokenValidationCheckFilter
        - id: socket
          uri: lb:ws://SOCKET
          predicates:
            - Path=/socket.io/

eureka:
  instance:
    instance-id: gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway