server:
  port: 8004

spring:
  application:
    name: s3
  profiles:
    active: prod
  config:
    import: ${SPRING_CONFIG_IMPORT}

eureka:
  instance:
    instance-id: s3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}